// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyVR24F3_RG9mD5XrqFqt1Qx2lGO25rrs',
    appId: '1:874868803867:web:9847e1bc52d5ffb2606bbe',
    messagingSenderId: '874868803867',
    projectId: 'nmap-personal',
    authDomain: 'nmap-personal.firebaseapp.com',
    storageBucket: 'nmap-personal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPe4t3BzI5ADAjIE3SvdxvJXB4KXRDt_g',
    appId: '1:874868803867:android:65b15ae8ddb8f78b606bbe',
    messagingSenderId: '874868803867',
    projectId: 'nmap-personal',
    storageBucket: 'nmap-personal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXzccP3BTdtdjVD8MG5-P4nqRBxu77gPk',
    appId: '1:874868803867:ios:68300a4008da97e2606bbe',
    messagingSenderId: '874868803867',
    projectId: 'nmap-personal',
    storageBucket: 'nmap-personal.appspot.com',
    iosClientId: '874868803867-5mp53832mlnoq8gemfmvukh7eciltugs.apps.googleusercontent.com',
    iosBundleId: 'com.example.nmapPersonal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXzccP3BTdtdjVD8MG5-P4nqRBxu77gPk',
    appId: '1:874868803867:ios:68300a4008da97e2606bbe',
    messagingSenderId: '874868803867',
    projectId: 'nmap-personal',
    storageBucket: 'nmap-personal.appspot.com',
    iosClientId: '874868803867-5mp53832mlnoq8gemfmvukh7eciltugs.apps.googleusercontent.com',
    iosBundleId: 'com.example.nmapPersonal',
  );
}
