// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM4TnCGcqx0knoOLcLXM8W4xeFcByrtek',
    appId: '1:711318654331:web:a60bc3533333465b11c1de',
    messagingSenderId: '711318654331',
    projectId: 'nmappersonal',
    authDomain: 'nmappersonal.firebaseapp.com',
    storageBucket: 'nmappersonal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ-9E-PdnUrgo5h4kbI03l9washdn2Oa0',
    appId: '1:711318654331:android:add64d8e9a78b79e11c1de',
    messagingSenderId: '711318654331',
    projectId: 'nmappersonal',
    storageBucket: 'nmappersonal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR02S-GZEjJ7JCbKyc6e_GMbluKJvGPGc',
    appId: '1:711318654331:ios:74ebfa2b42cd641c11c1de',
    messagingSenderId: '711318654331',
    projectId: 'nmappersonal',
    storageBucket: 'nmappersonal.appspot.com',
    androidClientId: '711318654331-evfvessdshspvt3olo6i75bcpepjsmp9.apps.googleusercontent.com',
    iosClientId: '711318654331-9vmqtcgdp6ir8b7f86dj4uiemrkjl5t4.apps.googleusercontent.com',
    iosBundleId: 'com.example.nmapPersonal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR02S-GZEjJ7JCbKyc6e_GMbluKJvGPGc',
    appId: '1:711318654331:ios:74ebfa2b42cd641c11c1de',
    messagingSenderId: '711318654331',
    projectId: 'nmappersonal',
    storageBucket: 'nmappersonal.appspot.com',
    androidClientId: '711318654331-evfvessdshspvt3olo6i75bcpepjsmp9.apps.googleusercontent.com',
    iosClientId: '711318654331-9vmqtcgdp6ir8b7f86dj4uiemrkjl5t4.apps.googleusercontent.com',
    iosBundleId: 'com.example.nmapPersonal',
  );
}
